### ISSUE TITLE
No module named l2tor_uwds_client

### ISSUE THREAD

**Issue by arlla** [tschodde/interactionmanager#1]
When I run ./interactionmanager.sh  in terminal(ubuntu 18.04),
following error occurs.  (I have converted interactionmanager.bat to interactionmanager.sh)

Traceback (most recent call last):
  File "interaction_manager.py", line 20, in <module>
    from l2tor_uwds_client import l2tor_uwds_client
ImportError: No module named l2tor_uwds_client
sleep: missing operand
Try 'sleep --help' for more information.

Please help me to resolve this.

**Comment by tschodde** [comment]
Hi there,
you need to install underworlds first, which isn't uploaded yet. It will be online in the next days/weeks. Please try again afterwards. 
Cheers

**Comment by arlla** [comment]
Thank you
